### ISSUE TITLE
Where should I put the GT.mat?

### ISSUE THREAD

**Issue by rubbishpeople** [Li-yachuan/eval-edge-pytorch#1]
thanks for your work, I have a question about the dir of Ground_truth. seems like i The dir of GT is fixed in readme?

**Comment by rubbishpeople** [comment]
I have get it， the structure should be ".../eval-edge-pytorch-main/GT (should self crate)/BSDS", While, new error : Start to eval result ...
****************************************
result
****************************************

result
Traceback (most recent call last):
  File "/content/eval-edge/eval.py", line 112, in <module>
    mian_func(args)
  File "/content/eval-edge/eval.py", line 77, in mian_func
    eval_one_epoch(parser_one_epoch)
  File "/content/eval-edge/eval_component.py", line 30, in eval_one_epoch
    nms_process(result_dir, nms_dir, key, file_format)
  File "/content/eval-edge/nms_process.py", line 65, in nms_process
    image = image[key]
KeyError: 'img'

**Comment by Li-yachuan** [comment]
Groundtruth is not needed during nms progress.&nbsp; I guess you use an error format of the predicted&nbsp;edge map.&nbsp; The format of edge map following&nbsp; the&nbsp; Official code of&nbsp; rcf



---Original---
From: ***@***.***&gt;
Date: Sun, Jun 16, 2024 15:34 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Li-yachuan/eval-edge-pytorch] Where should I put the GT.mat?(Issue #1)




 
I have get it， the structure should be ".../eval-edge-pytorch-main/GT (should self crate)/BSDS", While, new error : Start to eval result ...
 
 
result
 
 
result
 Traceback (most recent call last):
 File "/content/eval-edge/eval.py", line 112, in 
 mian_func(args)
 File "/content/eval-edge/eval.py", line 77, in mian_func
 eval_one_epoch(parser_one_epoch)
 File "/content/eval-edge/eval_component.py", line 30, in eval_one_epoch
 nms_process(result_dir, nms_dir, key, file_format)
 File "/content/eval-edge/nms_process.py", line 65, in nms_process
 image = image[key]
 KeyError: 'img'
